[package]
name = "tinyinst-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1.0", default-features = false, features = ["alloc"] }

[features]
path_check = []

[build-dependencies]
cmake = "0.1"
