[tasks.build_test]
dependencies = ["build_configure"]
cwd = "./test"
command = "cmake"
args = ["--build", "build", "--config", "Debug"]

[tasks.build_configure]
cwd = "./test"
command = "cmake"
args = ["-S", ".", "-B", "build"]
